apiVersion: cert-manager.io/v1

kind: Certificate

metadata:

  name: octosplay.com
  
  namespace: api

spec:

  secretName: octosplay.com-tls

  issuerRef:

    name: letsencrypt-prod

    kind: ClusterIssuer

  commonName: "*.octosplay.com"

  dnsNames:

  - "*.octosplay.com"