apiVersion: cert-manager.io/v1

kind: Certificate

metadata:

  name: octosplay.com
  
  namespace: api

spec:

  secretName: api.octosplay.com-tls

  issuerRef:

    name: octosplay-api-issuer

    kind: ClusterIssuer

  commonName: api.octosplay.com

  dnsNames:

  - api.octosplay.com