apiVersion: v1
kind: Namespace
metadata:
  name: api-staging
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5naXRsYWIuY29tIjp7InVzZXJuYW1lIjoiZ2xwYXQtU3J6eWtMMlBSeG0zeEJ5UWp0LTUiLCJwYXNzd29yZCI6ImdscGF0LVNyenlrTDJQUnhtM3hCeVFqdC01IiwiYXV0aCI6IloyeHdZWFF0VTNKNmVXdE1NbEJTZUcwemVFSjVVV3AwTFRVNloyeHdZWFF0VTNKNmVXdE1NbEJTZUcwemVFSjVVV3AwTFRVPSJ9fX0=
kind: Secret
metadata:
  name: regcred
  namespace: api-staging
type: kubernetes.io/dockerconfigjson
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: octosplayapi
  namespace: api-staging
  labels:
    octos-play: api-staging
  annotations:
    app-version: aplikasi ini di build dengan image versi satu
spec:
  replicas: 1
  selector:
    matchLabels:
      octosplay-replica: api-staging
  template:
    metadata:
      name: pod-api-staging
      labels:
        octosplay-replica: api-staging
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: octosplayapi
        image: registry.gitlab.com/octosplay/zukino:api-service3
        env:
        - name: APP_NAME
          value: "Laravel"
        - name: APP_ENV
          value: "local"
        - name: APP_KEY
          value: "base64:123456789101245q1vW4fCfzjFZyR5w8cwG5clMHZ1s="
        - name: APP_DEBUG
          value: "false"
        - name: APP_TIMEZONE
          value: "Asia/Jakarta"
        - name: APP_URL
          value: "http://localhost"
        #mysql env
        - name: DB_MEM_HOST
          value: "mysql-cluster.default.svc.cluster.local"
        - name: DB_MEM_PORT
          value: "3306"
        - name: DB_MEM_DATABASE
          value: "octosplay_client"
        - name: DB_MEM_USERNAME
          value: "root"
        - name: DB_MEM_PASSWORD
          value: "Zuk1no12345"
        - name: DB_MAS_HOST
          value: "mysql-cluster.default.svc.cluster.local"
        - name: DB_MAS_PORT
          value: "3306"
        - name: DB_MAS_DATABASE
          value: "octosplay_master"
        - name: DB_MAS_USERNAME
          value: "root"
        - name: DB_MAS_PASSWORD
          value: "Zuk1no12345"
        #mongodb env
        - name: MONGO_CP_URL
          value: "mongodb+srv://octosplay:Zuk1n0@mongodb-svc.mongodb.svc.cluster.local/admin?replicaSet=mongodb&ssl=false"
        - name: MONGO_CP_DBN
          value: "27017"
        - name: MONGO_LOG_URL
          value: "mongodb+srv://octosplay:Zuk1n0@mongodb-svc.mongodb.svc.cluster.local/admin?replicaSet=mongodb&ssl=false"
        - name: MONGO_TRX_URL
          value: "mongodb+srv://octosplay:Zuk1n0@mongodb-svc.mongodb.svc.cluster.local/admin?replicaSet=mongodb&ssl=false"
        - name: MONGO_TRX_DBN
          value: "transaction_db"
        - name: MONGO_LOG_DBN
          value: "logging_db"
        - name: MONGO_GAME_DBN
          value: "game_db"
        #568win api
        - name: WIN_COMPANYKEY
          value: "3C7FE217FC724A80859A474803C69FCA"
        - name: WIN_API
          value: "https://ex-api-demo-yy.568win.com"
        - name: WIN_SERVERID
          value: "octosplay"
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /api/ping
            port: 80
          initialDelaySeconds: 0
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1
          timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: apache2api-staging
  namespace: api-staging
  labels:
    octos-play: apache2api-staging
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    octosplay-replica: api-staging