apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mysqlserver
type: kubernetes.io/basic-auth
stringData:
  password: Zuk1n012345
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data
  namespace: mysqlserver
spec:
  storageClassName: rook-cephfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: mysqlserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        #- name: MYSQL_USER
          #value: "zukino"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-volume
          mountPath: /app/data
      volumes:
      - name: mysql-volume
        persistentVolumeClaim:
          claimName: mysql-data