apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysqlserver
  namespace: mysqlserver
  labels:
    type: local
spec:
  storageClassName: rook-cephfs
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: mysql-data
    namespace: mysqlserver