apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: mysqlserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        #- name: MYSQL_USER
          #value: "zukino"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-volume
          mountPath: /app/data
      volumes:
      - name: mysql-volume
        persistentVolumeClaim:
          claimName: mysql-data