apiVersion: v1
kind: Namespace
metadata:
  name: mysqlserver
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mysqlserver
type: kubernetes.io/basic-auth
stringData:
  password: Zuk1n012345
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: mysqlserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-volume
          mountPath: /app/data
      volumes:
      - name: mysql-volume
        hostPath:
          path: /data/mysql
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: mysqlserver
spec:
  type: LoadBalancer
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mysql