apiVersion: v1
kind: Secret
metadata:
  name: mongodb-password
type: Opaque
stringData:
  password: 'Zuk1n0'
---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb
spec:
  members: 3
  type: ReplicaSet
  version: "5.0.5"
  replicaSetHorizons:
  - horizon: mongodb-0.octosplay.com:27017
  - horizon: mongodb-1.octosplay.com:27017
  - horizon: mongodb-2.octosplay.com:27017
  security:
    authentication:
      modes: ["SCRAM"]
    tls:
      enabled: true
      certificateKeySecretRef:
        name: mongodb-tls
      caConfigMapRef:
        name: ca-config-map
  users:
    - name: octosplay
      db: admin
      passwordSecretRef:
        name: mongodb-password
      roles:
        - name: root
          db: admin
      scramCredentialsSecretName: my-scram
  statefulSet:
      spec:
        volumeClaimTemplates:
          - metadata:
              name: data-volume
            spec:
              accessModes: ["ReadWriteOnce"]
              storageClassName: vultr-block-storage
              resources:
                requests:
                  storage: 10Gi
          - metadata:
              name: logs-volume
            spec:
              accessModes: ["ReadWriteOnce"]
              storageClassName: vultr-block-storage
              resources:
                requests:
                  storage: 10Gi