apiVersion: v1
kind: Namespace
metadata:
  name: server
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5naXRsYWIuY29tIjp7InVzZXJuYW1lIjoiZ2xwYXQtdnJ0cGRMVG14ZmlMeld5c2VmXzciLCJwYXNzd29yZCI6ImdscGF0LXZydHBkTFRteGZpTHpXeXNlZl83IiwiZW1haWwiOiJ6dWtpbm9zdWtpbm9AZ21haWwuY29tIiwiYXV0aCI6IloyeHdZWFF0ZG5KMGNHUk1WRzE0Wm1sTWVsZDVjMlZtWHpjNloyeHdZWFF0ZG5KMGNHUk1WRzE0Wm1sTWVsZDVjMlZtWHpjPSJ9fX0=
kind: Secret
metadata:
  name: regcred
  namespace: server
type: kubernetes.io/dockerconfigjson
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: serveroctosplay
  namespace: server
  labels:
    udangbet: member
  annotations:
    octosplay: server
spec:
  replicas: 2
  selector:
    matchLabels:
      server-replica: server
  template:
    metadata:
      name: server-pod
      labels:
        server-replica: server
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: octosplayserver
        image: registry.gitlab.com/octosplay/server:1.0.5
        env:
        - name: APP_NAME
          value: "Octosplay"
        - name: APP_ENV
          value: "local"
        - name: APP_KEY
          value: "base64:123456789101245q1vW4fCfzjFZyR5w8cwG5clMHZ1s="
        - name: APP_DEBUG
          value: "true"
        - name: APP_URL
          value: "http://server.octosplay.com"
        #Server Env
        - name: API_URL
          value: "https://api.octosplay.com/api"
        - name: WEEKLY_BONUS_TOKEN
          value: "aaabbbccc"
        #Redis Env
        - name: REDIS_HOST
          value: "octosplay-redis-do-user-13616716-0.b.db.ondigitalocean.com"
        - name: REDIS_PASSWORD
          value: "AVNS_q9tt1TgyF5K9eGJTbAE"
        - name: REDIS_PORT
          value: "25061"
        #mysql env
        - name: DB_MEM_HOST
          value: "octosplay-mysql-do-user-13616716-0.b.db.ondigitalocean.com"
        - name: DB_MEM_PORT
          value: "25060"
        - name: DB_MEM_DATABASE
          value: "octosplay_client"
        - name: DB_MEM_USERNAME
          value: "octosplay"
        - name: DB_MEM_PASSWORD
          value: "AVNS_Vvd0cVgwap17PuWWlwb"
        - name: DB_MAS_HOST
          value: "octosplay-mysql-do-user-13616716-0.b.db.ondigitalocean.com"
        - name: DB_MAS_PORT
          value: "25060"
        - name: DB_MAS_DATABASE
          value: "octosplay_master"
        - name: DB_MAS_USERNAME
          value: "octosplay"
        - name: DB_MAS_PASSWORD
          value: "AVNS_Vvd0cVgwap17PuWWlwb"
        #mongodb env
        - name: MONGO_CP_URL
          value: "mongodb+srv://octosplay:B0C4jPauf6d21357@octosplay-mongodb-e0460298.mongo.ondigitalocean.com/admin?tls=true&authSource=admin&replicaSet=octosplay-mongodb"
        - name: MONGO_CP_DBN
          value: "27017"
        - name: MONGO_LOG_URL
          value: "mongodb+srv://octosplay:B0C4jPauf6d21357@octosplay-mongodb-e0460298.mongo.ondigitalocean.com/admin?tls=true&authSource=admin&replicaSet=octosplay-mongodb"
        - name: MONGO_TRX_URL
          value: "mongodb+srv://octosplay:B0C4jPauf6d21357@octosplay-mongodb-e0460298.mongo.ondigitalocean.com/admin?tls=true&authSource=admin&replicaSet=octosplay-mongodb"
        - name: MONGO_TRX_DBN
          value: "transaction_db"
        - name: MONGO_LOG_DBN
          value: "logging_db"
        - name: MONGO_GAME_DBN
          value: "game_db"
        # White Label Agent
        - name: WIN_AGENT
          value: "octosplayudangbetpro"
        # Firewall Application
        - name: FIREWALL_STATUS
          value: "false"
        - name: WHITE_LIST
          value: "45.76.188.6,127.0.0.1,103.60.252.203,103.60.252.204,103.60.252.250,103.60.253.203,103.60.253.205,103.60.253.249,103.60.254.250,34.80.251.105,43.198.1.150,52.194.35.1,13.208.136.250,122.146.58.49,61.220.125.7,61.220.125.8,111.235.225.61,111.235.225.62,125.227.48.247,125.227.48.248,103.130.140.170,163.47.15.15,103.60.253.249"
        - name: WEB_ALLOWED
          value: "udangbet.com"
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /api/ping
            port: 80
          initialDelaySeconds: 0
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1
          timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: apache-server
  namespace: server
  labels:
    server: apache-server
spec:
  selector:
    server-replica: server
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: server-ingress
  namespace: server
spec:
  rules:
  - host: server.octosplay.com
    http:
      paths:
      - backend:
          service:
            name: apache-server
            port:
              number: 80
        path: /
        pathType: Prefix
status:
  loadBalancer: {}