apiVersion: v1
kind: Namespace
metadata:
  name: mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodbdeploy
  namespace: mongodb
  labels:
    name: mongodbdeploy
spec:
  selector:
    matchLabels:
      pod: mongodb
  template:
    metadata:
      name: pod-mongodb
      labels:
        pod: mongodb
    spec:
      containers:
        - name: octosplaymongodb
          image: amd64/mongo
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "zukino"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "Zuk1n0"
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: mongodbvolume
      volumes:
        - name: mongodbvolume
          hostPath:
            path: /data/mongodb
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: mongodbserver
  namespace: mongodb
  labels:
    octosplay: mongodbservice
spec:
  type: LoadBalancer
  selector:
    pod: mongodb
  ports:
  - port: 27017
    targetPort: 27017