apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-data
  namespace: mongodb
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  storageClassName: rook-cephfs