apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodbstorageclaim
  namespace: mongodb
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 3Gi
  storageClassName: rook-ceph-block
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodbdeploy
  namespace: mongodb
  labels:
    name: mongodbdeploy
spec:
  selector:
    matchLabels:
      pod: mongodb
  #template for create new pod
  template:
    metadata:
      name: pod-mongodb
      labels:
        pod: mongodb
    #container spesification
    spec:
      containers:
        - name: octosplaymongodb
          image: amd64/mongo
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "zukino"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "Zuk1n0"
          #command: ["/bin/sh"]
          #args: ["-c", "mongod --replSet=rs0 --bind_ip_all"]
          ports:
            - containerPort: 27017
        #add presistent volume to container
          volumeMounts:
            - mountPath: /data/db
              name: mongodbvolume
        #Claim as Volume
      volumes:
        - name: mongodbvolume
          persistentVolumeClaim:
            claimName: mongodbstorageclaim