apiVersion: v1
kind: Service
metadata:
  name: mongodbbalancer
  namespace: mongodb
  labels:
    octosplay: mongodbbalancer
spec:
  type: LoadBalancer
  selector:
    pod: mongodbmaster
  ports:
    - port: 27017
      targetPort: 27017