apiVersion: v1
kind: Service
metadata:
  name: mongodbserver
  namespace: mongodb
  labels:
    octosplay: mongodbservice
spec:
  selector:
    pod: mongodbmaster
  ports:
  - port: 27017
    targetPort: 27017
  