apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodbstorageclaim2
  namespace: mongodb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-cephfs
---
apiVersion: v1
kind: Service
metadata:
  name: mongodbreplica2service
  namespace: mongodb
  labels:
    octosplay: mongodbservice
spec:
  selector:
    pod: mongodbreplica2
  ports:
  - port: 27017
    targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodbreplica2
  namespace: mongodb
  labels:
    name: mongodbreplica2
spec:
  selector:
    matchLabels:
      pod: mongodbreplica2
  #template for create new pod
  template:
    metadata:
      name: pod-mongodbreplica2
      labels:
        pod: mongodbreplica2
    #container spesification
    spec:
      containers:
        - name: mongodbreplica2
          image: amd64/mongo
          command: ["/bin/sh"]
          args: ["-c", "mongod --replSet rs0"]
          ports:
            - containerPort: 27017
        #add presistent volume to container
          volumeMounts:
            - mountPath: /data/db
              name: mongodbvolume2
        #Claim as Volume
      volumes:
        - name: mongodbvolume2
          persistentVolumeClaim:
            claimName: mongodbstorageclaim2
            readOnly: false