apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: octosplay-api-issuer
  namespace: api
  labels:
    octos-play: api-issuer
spec:
  acme:
    email: cs@otosplay.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: octosplay-screet
    solvers:
      # Use the HTTP-01 challenge provider
      - http01:
          ingress:
            class: nginx