apiVersion: v1
kind: Namespace
metadata:
  name: member
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5naXRsYWIuY29tIjp7InVzZXJuYW1lIjoiZ2xwYXQtU3J6eWtMMlBSeG0zeEJ5UWp0LTUiLCJwYXNzd29yZCI6ImdscGF0LVNyenlrTDJQUnhtM3hCeVFqdC01IiwiYXV0aCI6IloyeHdZWFF0VTNKNmVXdE1NbEJTZUcwemVFSjVVV3AwTFRVNloyeHdZWFF0VTNKNmVXdE1NbEJTZUcwemVFSjVVV3AwTFRVPSJ9fX0=
kind: Secret
metadata:
  name: regcred
  namespace: member
type: kubernetes.io/dockerconfigjson
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: octosplaymember
  namespace: member
  labels:
    octos-play: member
  annotations:
    app-version: aplikasi ini di build dengan image versi satu
spec:
  replicas: 3
  selector:
    matchLabels:
      octosplay-replica: member
  template:
    metadata:
      name: pod-member
      labels:
        octosplay-replica: member
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: octosplaymember
        image: registry.gitlab.com/octosplay/zukino:udangbet
        env:
        - name: APP_NAME
          value: "Octosplay"
        - name: APP_ENV
          value: "production"
        - name: APP_KEY
          value: "base64:XVb0v4IcNSNFvNsrrZTexyz60/p9N7EIjbm2Qi8ia/I="
        - name: APP_DEBUG
          value: "true"
        - name: APP_URL
          value: "https://member.octosplay.com"
        - name: API_URL
          value: "https://apps.octosplay.com/api"
        - name: GAME_URL
          value: "https://api.octosplay.com/api"
        - name: REDIS_URL
          value: "rediss://default:AVNS_N78vpi9F8eAwcXz2utR@testing-redis-do-user-6322205-0.b.db.ondigitalocean.com:25061?database=0"
        - name: REDIS_CACHE
          value: "rediss://default:AVNS_N78vpi9F8eAwcXz2utR@testing-redis-do-user-6322205-0.b.db.ondigitalocean.com:25061?database=1"
        - name: EXPIRED_TIME_MINUTE
          value: "5000"
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /api/ping
            port: 80
          initialDelaySeconds: 0
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1
          timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: phpfpm-member
  namespace: member
  labels:
    octos-play: phpfpm-member
spec:
  selector:
    octosplay-replica: member
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: member-prod
  namespace: member
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: hernandessukino94@gmail.com
    privateKeySecretRef:
      name: member-prod
    solvers:
    - http01:
        ingress:
          class: traefik
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: octosplay.com
  namespace: member
spec:
  secretName: udangbet.com-tls
  issuerRef:
    name: member-prod
    kind: ClusterIssuer
  commonName: udangbet.com
  dnsNames:
  - udangbet.com
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: member-prod
    kubernetes.io/ingress.class: traefik
  name: member-ingress
  namespace: member
spec:
  rules:
  - host: udangbet.com
    http:
      paths:
      - backend:
          service:
            name: phpfpm-member
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - udangbet.com
    secretName: udangbet.com-tls
status:
  loadBalancer: {}