---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zukinocephfsclaim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem
