apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodbserver
  namespace: mongodb
spec:
  statefulSet:
    spec:
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            accessModes: ["ReadWriteOnce"]
            storageClassName: rook-ceph-block
            resources:
              requests:
                storage: 2Gi
        - metadata:
            name: logs-volume
          spec:
            accessModes: [ "ReadWriteOnce" ]
            storageClassName: rook-ceph-block
            resources:
              requests:
                storage: 2Gi
  members: 2
  type: ReplicaSet
  version: "4.2.6"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: zukino
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: mongodbsecrets
      roles:
        - name: root
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: zukinoscram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib

# the user credentials will be generated from this secret
# once the credentials are generated, this secret is no longer required
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodbsecrets
  namespace: mongodb
type: Opaque
stringData:
  password: "Zuk1n0"
