apiVersion: v1
kind: Service
metadata:
  name: mongodbserver
  namespace: mongodb
  labels:
    octosplay: mongodbservice
spec:
  type: LoadBalancer
  selector:
    app: mongodbserver-svc
  ports:
  - port: 27017
    targetPort: 27017
  